source 'https://cdn.cocoapods.org'
source 'http://code.zaoing.com/meeting/freewindSpecs.git'
platform :ios, '9.0'

# 忽略引入库的所有警告
inhibit_all_warnings!
use_frameworks!

def commonPods
  # 本地依赖FWSuperPlayerSDK
  pod 'FWSuperPlayerSDK', :path => '../'
  # SDK远程依赖
  # pod 'FWSuperPlayerSDK'
end

target 'FWSuperPlayerSDK_Example' do
    commonPods
end
