use_frameworks!

platform :ios, '9.0'

target 'FWSuperPlayerSDK_Example' do
  pod 'FWSuperPlayerSDK', :path => '../'

  target 'FWSuperPlayerSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
